apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ticket-3-testing
  namespace: argocd
spec:
  project: default
  source:
    path: testing/review-app
    repoURL: https://github.com/weydenherrera/sample-app-k8s.git
    targetRevision: ticket-3-testing
  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-3-testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
