apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ticket-2-testing
spec:
  ports:
  - port: 4000
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ticket-2-testing
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: weydenherrera/sample-app:2023-01-20_08-32-49.218_PST
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 4000
